### PR TITLE
Add XSD.Base64Binary

### PR DESCRIPTION
**Pull request by pukkamustard**
This adds the xsd:base64Binary data type.

In Elixir this is basically xsd:string with a different lexical form.

### CODE REVIEW

**Comment by pukkamustard** [comment]
My spec-foo is very limited. I need some help with the dialyzer issue.

**Comment by marcelotto** [comment]
Sorry, noticed your PR just today. (I'm getting too much GitHub notifications.) 

Looking good overall. However, the handling of the error result case of the `Base.decode64/1` call in `lexical_mapping/2` doesn't seem right. Trying to reinterpret the string in that case as the unencoded form is an unsatisfactory solution for the problem that we can't really differentiate encoded from unencoded strings. What's with unencoded strings that can be interpreted as encoded strings coincidentally or with really erroneous encoded strings? The datatype system is lacking a general method to deal with datatypes where the value space consists of strings which are different from the lexical space.

I'll take a further look into this over the weekend.

> My spec-foo is very limited. I need some help with the dialyzer issue.

I guess it has something to do with the fact that your `elixir_mapping` implementation with the `is_binary` clause will never be called.

**Comment by marcelotto** [comment]
I've added on flag option `:as_value` which allows to enforce the interpretation of a string as a value (instead of a lexical). This should allow a proper implementation where you can now return `@invalid_value` in the error case of `lexical_mapping`. In the `is_binary` clause of  the `elixir_mapping` implementation you can simply return `value`. No need to do the canonical mapping there.

**Comment by pukkamustard** [comment]
> I've added a flag option :as_value which allows to enforce the interpretation of a string as a value (instead of a lexical).

Thank you very much! This does the trick.

> This should allow a proper implementation where you can now return @invalid_value in the error case of lexical_mapping. In the is_binary clause of the elixir_mapping implementation you can simply return value. No need to do the canonical mapping there.

Pushed.

> Could you please add some tests for above mentioned edge cases (unencoded strings that can be interpreted as encoded strings coincidentally and erroneous encoded strings) both with and without the use of the new option.

Done. Added some tests with the `valid` and `invalid` fields, as well as two manual tests that use the `:as_value` flag.

Hope to have caught all edge-cases. Do you see any more?

> I guess it has something to do with the fact that your elixir_mapping implementation with the is_binary clause will never be called.

Problem seemed to be with `init_valid_lexical`, which does not seem to be necessary anyway. Removing it solves the dialyzer issue.

**Comment by marcelotto** [comment]
👍 Perfect. Thanks for the contribution.

**Pull request merged**
